// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/bysnupy/maintpage-operator/pkg/apis/maintpage/v1alpha1.MaintPage":       schema_pkg_apis_maintpage_v1alpha1_MaintPage(ref),
		"github.com/bysnupy/maintpage-operator/pkg/apis/maintpage/v1alpha1.MaintPageSpec":   schema_pkg_apis_maintpage_v1alpha1_MaintPageSpec(ref),
		"github.com/bysnupy/maintpage-operator/pkg/apis/maintpage/v1alpha1.MaintPageStatus": schema_pkg_apis_maintpage_v1alpha1_MaintPageStatus(ref),
	}
}

func schema_pkg_apis_maintpage_v1alpha1_MaintPage(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MaintPage is the Schema for the maintpages API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/bysnupy/maintpage-operator/pkg/apis/maintpage/v1alpha1.MaintPageSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/bysnupy/maintpage-operator/pkg/apis/maintpage/v1alpha1.MaintPageStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/bysnupy/maintpage-operator/pkg/apis/maintpage/v1alpha1.MaintPageSpec", "github.com/bysnupy/maintpage-operator/pkg/apis/maintpage/v1alpha1.MaintPageStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_maintpage_v1alpha1_MaintPageSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MaintPageSpec defines the desired state of MaintPage",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_maintpage_v1alpha1_MaintPageStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MaintPageStatus defines the observed state of MaintPage",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
