apiVersion: maintpage.example.com/v1alpha1
kind: MaintPage
metadata:
  name: example
spec:
  maintpageconfig:
    maintpagetoggle: false
    maintpageimage: quay.io/daein/maintpage:latest
  appconfig:  
    appname: httpd
    appimage: quay.io/daein/prodpage:latest
