apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintpage-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: maintpage-operator
  template:
    metadata:
      labels:
        name: maintpage-operator
    spec:
      serviceAccountName: maintpage-operator
      containers:
        - name: maintpage-operator
          # Replace this with the built image name
          image: quay.io/daein/maintpage-operator:v0.1.1
          command:
          - maintpage-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "maintpage-operator"
