---
apiVersion: v1
kind: Service
metadata:
  name: maintpage
  labels:
    app: maintpage
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: maintpage
  typr: ClusterIP
